disable:
  triggers: true

repositories:
- name: kogito-pipelines
- name: kogito-runtimes
- name: kogito-apps
- name: kogito-examples

job_types:
  setup-branch:
    disabled: true
  nightly:
    disabled: true
  other:
    disabled: false
  pullrequest:
    disabled: false
  release:
    disabled: true
  tools:
    disabled: true

git:
  author:
    name: mbiarnes
    credentials_id: mbiarnes
    token_credentials_id: mbiarnes-gh-token
  fork_author:
    name: mbiarnes
    credentials_id: mbiarnes
  jenkins_config_path: .ci/jenkins

buildchain_config:
  git:
    repository: kogito-pipelines
    file_path: .ci/pull-request-config.yaml

maven:
  settings_file_id: kogito_release_settings
  nexus:
    release_url: https://repository.stage.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.stage.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: 1966c60aff37d
  artifacts_repository: ''
  artifacts_upload_repository:
    url: https://repository.jboss.org/nexus/content/repositories/snapshots/
    creds_id: kogito-snapshots-upload
  quarkus_platform_repository:
    url: https://repository.jboss.org/nexus/content/repositories/kogito-internal-repository/
    creds_id: kogito-internal-nexus-creds

cloud:
  image:
    registry_credentials_nightly: nightly_kogito
    registry_credentials_release: release_kogito
    registry: quay.io
    namespace: kiegroup
    latest_git_branch: main

jenkins:
  email_creds_id: MBIARNES_MAIL
  default_tools:
    jdk: kie-jdk11
    maven: kie-maven-3.8.7
    sonar_jdk: kie-jdk17
  jobs_definition_file: .ci/jenkins/dsl/jobs.groovy
